In [17]:
import numpy as np
import pandas as pd
from IPython.display import display, HTML

from uot.analysis import get_agg_table, get_comparison_table, get_mean_comparison_table, get_std_comparison_table

# Comparison of OT algorithms

1. Own implemented Sinkhorn with jax
2. OTT-JAX Sinkhorn
3. LP

In [2]:
sinkhorn_df = pd.read_csv("./results/sinkhorn.csv")
ott_jax_sinkhorn_df = pd.read_csv("./results/ott_jax_sinkhorn.csv")
pot_lp_df = pd.read_csv("./results/pot_lp.csv")
pot_sinkhorn_df = pd.read_csv("./results/pot_sinkhorn.csv")

ott_jax_sinkhorn_df.drop(index=0, inplace=True)
sinkhorn_df.drop(index=0, inplace=True)

In [3]:
proper_order = ['32 1D Gaussians', '64 1D Gaussians', '128 1D Gaussians', '512 1D Gaussians',
                '4x4 2D Gaussians', '8x8 2D Gaussians', '16x16 2D Gaussians', '32x32 2D Gaussians'] 

def make_comlexity_order(df):
    df['name'] = pd.Categorical(df['name'], categories=proper_order, ordered=True)
    return df.sort_values('name')

In [4]:
for test_name in proper_order:
    ott_index = ott_jax_sinkhorn_df[ott_jax_sinkhorn_df.name == test_name].iloc[:1].index
    sink_index = ott_jax_sinkhorn_df[ott_jax_sinkhorn_df.name == test_name].iloc[:1].index
    ott_jax_sinkhorn_df.drop(index=ott_index, inplace=True)
    sinkhorn_df.drop(index=sink_index, inplace=True)

In [5]:
sinkhorn_agg = make_comlexity_order(get_agg_table(sinkhorn_df))
ott_jax_sinkhorn_agg = make_comlexity_order(get_agg_table(ott_jax_sinkhorn_df))
pot_lp_agg = make_comlexity_order(get_agg_table(pot_lp_df))
pot_sinkhorn_agg = make_comlexity_order(get_agg_table(pot_sinkhorn_df))

agg_dfs = {
    "jax_sinkhorn": sinkhorn_agg,
    "ottjax_sinkhorn": ott_jax_sinkhorn_agg,
    "pot_sinkhorn": pot_sinkhorn_agg,
    "pot_lp": pot_lp_agg
}

In [27]:
def display_mean_and_std(agg_dfs, column: str):
    mean_comparison = get_mean_comparison_table(agg_dfs, column)
    std_comparison = get_std_comparison_table(agg_dfs, column)

    mean_html = mean_comparison.style.highlight_min(axis=1, subset=mean_comparison.columns[1:],
                                    props='color:white; font-weight:bold; background-color:darkblue;').to_html()

    std_html = std_comparison.style.highlight_min(axis=1, subset=std_comparison.columns[1:],
                                    props='color:white; font-weight:bold; background-color:darkblue;').to_html()

    combined_html = f"""
    <h3 style="text-align:center;">{column} mean and std</h3>
    <div style="display: flex; justify-content: space-around;">
        <div>{mean_html}</div>
        <div>{std_html}</div>
    </div>
    """
    return display(HTML(combined_html))

In [28]:
display_mean_and_std(agg_dfs, "time")

In [29]:
display_mean_and_std(agg_dfs, "cost_rerr")

In [30]:
display_mean_and_std(agg_dfs, "coupling_avg_err")

In [31]:
display_mean_and_std(agg_dfs, "memory")