In [13]:

from uot.suites import time_precision_suite, memory_suite
from algorithms.lp import pot_lp
from uot.experiment import run_experiment
from algorithms.sinkhorn import sinkhorn, ott_jax_sinkhorn, pot_sinkhorn
from algorithms.gradient_ascent import gradient_ascent

from uot.analysis import display_all_metrics

In [14]:

import jax
jax.config.update("jax_enable_x64", True)

# Time and precision exeriments

### Solvers

In [15]:
solvers = {
    'pot-lp': pot_lp,
    'pot-sinkhorn': pot_sinkhorn,
    'ott-jax-sinkhorn': ott_jax_sinkhorn,
    'jax-sinkhorn': sinkhorn,
    'optax-grad-ascent': gradient_ascent
}

### Gamma distribution test

In [16]:
problemset_names = [
    "32 1D gamma",
    "64 1D gamma",
    "128 1D gamma",
    "256 1D gamma",
    "512 1D gamma",
]

results = run_experiment(time_precision_suite, problemset_names, solvers)
display_all_metrics(results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data loaded from ./datasets/1D/32_gamma.pkl
Data loaded from ./datasets/1D/64_gamma.pkl
Data loaded from ./datasets/1D/128_gamma.pkl
Data loaded from ./datasets/1D/256_gamma.pkl
Data loaded from ./datasets/1D/512_gamma.pkl

Running experiments: 100%|██████████| 2250/2250 [04:02<00:00,  9.27it/s]

### Beta distribution test

In [ ]:
problemset_names = [
    "32 1D beta",
    "64 1D beta",
    "128 1D beta",
    "256 1D beta",
    "512 1D beta",
    "1024 1D beta",
]

results = run_experiment(time_precision_suite, problemset_names, solvers)

display_all_metrics(results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data loaded from ./datasets/1D/32_beta.pkl
Data loaded from ./datasets/1D/64_beta.pkl
Data loaded from ./datasets/1D/128_beta.pkl
Data loaded from ./datasets/1D/256_beta.pkl
Data loaded from ./datasets/1D/512_beta.pkl

Running experiments: 100%|██████████| 1800/1800 [00:12<00:00, 144.56it/s]

### Different distributions

In [ ]:
problemset_names = [
    "32 1D gaussian|uniform|gamma|beta|cauchy",
    "64 1D gaussian|uniform|gamma|beta|cauchy",
    "128 1D gaussian|uniform|gamma|beta|cauchy",
    "256 1D gaussian|uniform|gamma|beta|cauchy",
    "512 1D gaussian|uniform|gamma|beta|cauchy"
    "1024 1D gaussian|uniform|gamma|beta|cauchy"
]

results = run_experiment(time_precision_suite, problemset_names, solvers)
display_all_metrics(results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data loaded from ./datasets/1D/32_beta_cauchy_gamma_gaussian_uniform.pkl
Data loaded from ./datasets/1D/64_beta_cauchy_gamma_gaussian_uniform.pkl
Data loaded from ./datasets/1D/128_beta_cauchy_gamma_gaussian_uniform.pkl
Data loaded from ./datasets/1D/256_beta_cauchy_gamma_gaussian_uniform.pkl
Data loaded from ./datasets/1D/512_beta_cauchy_gamma_gaussian_uniform.pkl

Running experiments:  31%|███▏      | 566/1800 [00:22<04:24,  4.66it/s] /home/zhukowych/.virtualenvs/ml/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:643: UserWarning: Warning: numerical errors at iteration 40
  warnings.warn("Warning: numerical errors at iteration %d" % ii)
Running experiments: 100%|██████████| 1800/1800 [01:48<00:00, 16.52it/s]