In [4]:
import os
os.environ["JAX_PLATFORMS"] = "cpu"

import jax
jax.config.update("jax_enable_x64", True)

from uot.suites import time_precision_suite, memory_suite
from algorithms.lp import pot_lp
from uot.experiment import run_experiment, get_problemset
from algorithms.sinkhorn import jax_sinkhorn, ott_jax_sinkhorn, pot_sinkhorn
from algorithms.gradient_ascent import gradient_ascent

from uot.analysis import display_all_metrics

# Time and precision exeriments

### Solvers

In [5]:
solvers = {
    'pot-lp': pot_lp,
    'ott-jax-sinkhorn': ott_jax_sinkhorn,
    'jax-sinkhorn': jax_sinkhorn,
    'optax-grad-ascent': gradient_ascent
}

### Gaussian distributions

In [6]:
problemset_names = [
    "64 1D gaussian",
    "128 1D gaussian",
    "256 1D gaussian",
    "512 1D gaussian",
    "1024 1D gaussian"
]

gaussian_results = run_experiment(time_precision_suite, problemset_names, solvers)
display_all_metrics(gaussian_results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data loaded from ./datasets/1D/64_gaussian.pkl
Data loaded from ./datasets/1D/128_gaussian.pkl
Data loaded from ./datasets/1D/256_gaussian.pkl
Data loaded from ./datasets/1D/512_gaussian.pkl
Data loaded from ./datasets/1D/1024_gaussian.pkl

Running experiments: 100%|██████████| 900/900 [03:11<00:00,  4.70it/s]

### Gamma distribution test

In [7]:
problemset_names = [
    "32 1D gamma",
    "64 1D gamma",
    "128 1D gamma",
    "256 1D gamma",
    "512 1D gamma",
    "1024 1D gamma"
]

gamma_results = run_experiment(time_precision_suite, problemset_names, solvers)
display_all_metrics(gamma_results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data saved to ./datasets/1D/32_gamma.pkl
Data saved to ./datasets/1D/64_gamma.pkl
Data saved to ./datasets/1D/128_gamma.pkl
Data saved to ./datasets/1D/256_gamma.pkl
Data saved to ./datasets/1D/512_gamma.pkl
Data saved to ./datasets/1D/1024_gamma.pkl

Running experiments:   0%|          | 0/1080 [00:00<?, ?it/s]

Running experiments: 100%|██████████| 1080/1080 [02:17<00:00,  7.87it/s]

### Beta distribution test

In [8]:
problemset_names = [
    "32 1D beta",
    "64 1D beta",
    "128 1D beta",
    "256 1D beta",
    "512 1D beta",
    "1024 1D beta",
]

beta_results = run_experiment(time_precision_suite, problemset_names, solvers)

display_all_metrics(beta_results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data saved to ./datasets/1D/32_beta.pkl
Data saved to ./datasets/1D/64_beta.pkl
Data saved to ./datasets/1D/128_beta.pkl
Data saved to ./datasets/1D/256_beta.pkl
Data saved to ./datasets/1D/512_beta.pkl
Data saved to ./datasets/1D/1024_beta.pkl

Running experiments:   0%|          | 0/1080 [00:00<?, ?it/s]

Running experiments:  20%|██        | 221/1080 [00:01<00:08, 96.88it/s] /home/zhukowych/.virtualenvs/ml/lib/python3.12/site-packages/ot/lp/__init__.py:388: UserWarning: numItermax reached before optimality. Try to increase numItermax.
  result_code_string = check_result(result_code)
Running experiments: 100%|██████████| 1080/1080 [06:51<00:00,  2.62it/s]

### Mixed distributions

In [9]:
problemset_names = [
    "32 1D gaussian|uniform|gamma|beta|cauchy",
    "64 1D gaussian|uniform|gamma|beta|cauchy",
    "128 1D gaussian|uniform|gamma|beta|cauchy",
    "256 1D gaussian|uniform|gamma|beta|cauchy",
    "512 1D gaussian|uniform|gamma|beta|cauchy",
    "1024 1D gaussian|uniform|gamma|beta|cauchy"
]

mixed_results = run_experiment(time_precision_suite, problemset_names, solvers)
display_all_metrics(mixed_results, ['time', 'cost_rerr', 'coupling_avg_err'])

Data saved to ./datasets/1D/32_beta_cauchy_gamma_gaussian_uniform.pkl
Data saved to ./datasets/1D/64_beta_cauchy_gamma_gaussian_uniform.pkl
Data saved to ./datasets/1D/128_beta_cauchy_gamma_gaussian_uniform.pkl
Data saved to ./datasets/1D/256_beta_cauchy_gamma_gaussian_uniform.pkl
Data saved to ./datasets/1D/512_beta_cauchy_gamma_gaussian_uniform.pkl
Data saved to ./datasets/1D/1024_beta_cauchy_gamma_gaussian_uniform.pkl

Running experiments:   0%|          | 0/1080 [00:00<?, ?it/s]

Running experiments:  20%|██        | 216/1080 [00:02<00:16, 52.88it/s] /home/zhukowych/.virtualenvs/ml/lib/python3.12/site-packages/ot/lp/__init__.py:388: UserWarning: numItermax reached before optimality. Try to increase numItermax.
  result_code_string = check_result(result_code)
Running experiments: 100%|██████████| 1080/1080 [02:17<00:00,  7.88it/s]